/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetricsShiftBids;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics
 */
public class EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetricsTest {
    private final EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics model = new EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics();

    /**
     * Model tests for EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics
     */
    @Test
    public void testEngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics() {
        // TODO: test EngageOverviewByLocationIdResponseDataEngagementScoresMostEngagedInnerMetrics
    }

    /**
     * Test the property 'shiftBids'
     */
    @Test
    public void shiftBidsTest() {
        // TODO: test shiftBids
    }

    /**
     * Test the property 'droppedShifts'
     */
    @Test
    public void droppedShiftsTest() {
        // TODO: test droppedShifts
    }

    /**
     * Test the property 'noShows'
     */
    @Test
    public void noShowsTest() {
        // TODO: test noShows
    }

    /**
     * Test the property 'lates'
     */
    @Test
    public void latesTest() {
        // TODO: test lates
    }

    /**
     * Test the property 'totalShifts'
     */
    @Test
    public void totalShiftsTest() {
        // TODO: test totalShifts
    }

}
