/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerTotal;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner
 */
public class ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerTest {
    private final ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner model = new ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner();

    /**
     * Model tests for ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner
     */
    @Test
    public void testReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner() {
        // TODO: test ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInner
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'weekLabel'
     */
    @Test
    public void weekLabelTest() {
        // TODO: test weekLabel
    }

    /**
     * Test the property 'dayLabel'
     */
    @Test
    public void dayLabelTest() {
        // TODO: test dayLabel
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'breaks'
     */
    @Test
    public void breaksTest() {
        // TODO: test breaks
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'locationLabel'
     */
    @Test
    public void locationLabelTest() {
        // TODO: test locationLabel
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'roleLabel'
     */
    @Test
    public void roleLabelTest() {
        // TODO: test roleLabel
    }

    /**
     * Test the property 'wage'
     */
    @Test
    public void wageTest() {
        // TODO: test wage
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'salaried'
     */
    @Test
    public void salariedTest() {
        // TODO: test salaried
    }

    /**
     * Test the property 'complianceExceptions'
     */
    @Test
    public void complianceExceptionsTest() {
        // TODO: test complianceExceptions
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
