/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerRolesInner;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerTotal;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerUser;
import com.konfigthis.client.model.ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportsGetWorkedHoursWagesResponseUsersInner
 */
public class ReportsGetWorkedHoursWagesResponseUsersInnerTest {
    private final ReportsGetWorkedHoursWagesResponseUsersInner model = new ReportsGetWorkedHoursWagesResponseUsersInner();

    /**
     * Model tests for ReportsGetWorkedHoursWagesResponseUsersInner
     */
    @Test
    public void testReportsGetWorkedHoursWagesResponseUsersInner() {
        // TODO: test ReportsGetWorkedHoursWagesResponseUsersInner
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'weeks'
     */
    @Test
    public void weeksTest() {
        // TODO: test weeks
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'salaried'
     */
    @Test
    public void salariedTest() {
        // TODO: test salaried
    }

}
