/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
 */
public class TaskManagementListTaskListsSummary200ResponseDataTaskListsInnerTest {
    private final TaskManagementListTaskListsSummary200ResponseDataTaskListsInner model = new TaskManagementListTaskListsSummary200ResponseDataTaskListsInner();

    /**
     * Model tests for TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
     */
    @Test
    public void testTaskManagementListTaskListsSummary200ResponseDataTaskListsInner() {
        // TODO: test TaskManagementListTaskListsSummary200ResponseDataTaskListsInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'completionStatus'
     */
    @Test
    public void completionStatusTest() {
        // TODO: test completionStatus
    }

    /**
     * Test the property 'totalTasksCompleted'
     */
    @Test
    public void totalTasksCompletedTest() {
        // TODO: test totalTasksCompleted
    }

    /**
     * Test the property 'totalTasks'
     */
    @Test
    public void totalTasksTest() {
        // TODO: test totalTasks
    }

    /**
     * Test the property 'completionPercentage'
     */
    @Test
    public void completionPercentageTest() {
        // TODO: test completionPercentage
    }

}
