/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TaskManagementCreateTaskListTemplateRequestAssignmentsInner;
import com.konfigthis.client.model.TaskManagementEditTaskListTemplateRequestTaskTemplatesInner;
import com.konfigthis.client.model.TaskManagementEditTaskListTemplateRequestTimeFrame;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaskManagementEditTaskListTemplateRequest
 */
public class TaskManagementEditTaskListTemplateRequestTest {
    private final TaskManagementEditTaskListTemplateRequest model = new TaskManagementEditTaskListTemplateRequest();

    /**
     * Model tests for TaskManagementEditTaskListTemplateRequest
     */
    @Test
    public void testTaskManagementEditTaskListTemplateRequest() {
        // TODO: test TaskManagementEditTaskListTemplateRequest
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'taskTemplates'
     */
    @Test
    public void taskTemplatesTest() {
        // TODO: test taskTemplates
    }

    /**
     * Test the property 'recurrence'
     */
    @Test
    public void recurrenceTest() {
        // TODO: test recurrence
    }

    /**
     * Test the property 'assignments'
     */
    @Test
    public void assignmentsTest() {
        // TODO: test assignments
    }

    /**
     * Test the property 'due'
     */
    @Test
    public void dueTest() {
        // TODO: test due
    }

    /**
     * Test the property 'timeFrame'
     */
    @Test
    public void timeFrameTest() {
        // TODO: test timeFrame
    }

}
