/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInnerFiltersInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner
 */
public class TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInnerTest {
    private final TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner model = new TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner();

    /**
     * Model tests for TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner
     */
    @Test
    public void testTipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner() {
        // TODO: test TipPoolGetSettingsResponseDataInnerTipPoolStakeholdersInner
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'tipPoolSettingsUuid'
     */
    @Test
    public void tipPoolSettingsUuidTest() {
        // TODO: test tipPoolSettingsUuid
    }

    /**
     * Test the property 'stakeholderType'
     */
    @Test
    public void stakeholderTypeTest() {
        // TODO: test stakeholderType
    }

    /**
     * Test the property 'stakeholderSubtype'
     */
    @Test
    public void stakeholderSubtypeTest() {
        // TODO: test stakeholderSubtype
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'departmentId'
     */
    @Test
    public void departmentIdTest() {
        // TODO: test departmentId
    }

    /**
     * Test the property 'stakeAmount'
     */
    @Test
    public void stakeAmountTest() {
        // TODO: test stakeAmount
    }

    /**
     * Test the property 'contributionMethod'
     */
    @Test
    public void contributionMethodTest() {
        // TODO: test contributionMethod
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

}
