/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * IntegrationMappingsListSalesCategoryMappingsResponseDataInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class IntegrationMappingsListSalesCategoryMappingsResponseDataInner {
  public static final String SERIALIZED_NAME_LOCATION_ID = "location_id";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private Integer locationId;

  public static final String SERIALIZED_NAME_DEPARTMENT_ID = "department_id";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT_ID)
  private Integer departmentId;

  public static final String SERIALIZED_NAME_EXTERNAL_CATEGORY_ID = "external_category_id";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_CATEGORY_ID)
  private String externalCategoryId;

  public IntegrationMappingsListSalesCategoryMappingsResponseDataInner() {
  }

  public IntegrationMappingsListSalesCategoryMappingsResponseDataInner locationId(Integer locationId) {
    
    
    
    
    this.locationId = locationId;
    return this;
  }

   /**
   * Location ID
   * @return locationId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Location ID")

  public Integer getLocationId() {
    return locationId;
  }


  public void setLocationId(Integer locationId) {
    
    
    
    this.locationId = locationId;
  }


  public IntegrationMappingsListSalesCategoryMappingsResponseDataInner departmentId(Integer departmentId) {
    
    
    
    
    this.departmentId = departmentId;
    return this;
  }

   /**
   * Department ID
   * @return departmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "Department ID")

  public Integer getDepartmentId() {
    return departmentId;
  }


  public void setDepartmentId(Integer departmentId) {
    
    
    
    this.departmentId = departmentId;
  }


  public IntegrationMappingsListSalesCategoryMappingsResponseDataInner externalCategoryId(String externalCategoryId) {
    
    
    
    
    this.externalCategoryId = externalCategoryId;
    return this;
  }

   /**
   * External Category ID
   * @return externalCategoryId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "External Category ID")

  public String getExternalCategoryId() {
    return externalCategoryId;
  }


  public void setExternalCategoryId(String externalCategoryId) {
    
    
    
    this.externalCategoryId = externalCategoryId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the IntegrationMappingsListSalesCategoryMappingsResponseDataInner instance itself
   */
  public IntegrationMappingsListSalesCategoryMappingsResponseDataInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationMappingsListSalesCategoryMappingsResponseDataInner integrationMappingsListSalesCategoryMappingsResponseDataInner = (IntegrationMappingsListSalesCategoryMappingsResponseDataInner) o;
    return Objects.equals(this.locationId, integrationMappingsListSalesCategoryMappingsResponseDataInner.locationId) &&
        Objects.equals(this.departmentId, integrationMappingsListSalesCategoryMappingsResponseDataInner.departmentId) &&
        Objects.equals(this.externalCategoryId, integrationMappingsListSalesCategoryMappingsResponseDataInner.externalCategoryId)&&
        Objects.equals(this.additionalProperties, integrationMappingsListSalesCategoryMappingsResponseDataInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationId, departmentId, externalCategoryId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationMappingsListSalesCategoryMappingsResponseDataInner {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    externalCategoryId: ").append(toIndentedString(externalCategoryId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("location_id");
    openapiFields.add("department_id");
    openapiFields.add("external_category_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("location_id");
    openapiRequiredFields.add("department_id");
    openapiRequiredFields.add("external_category_id");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to IntegrationMappingsListSalesCategoryMappingsResponseDataInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!IntegrationMappingsListSalesCategoryMappingsResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IntegrationMappingsListSalesCategoryMappingsResponseDataInner is not found in the empty JSON string", IntegrationMappingsListSalesCategoryMappingsResponseDataInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IntegrationMappingsListSalesCategoryMappingsResponseDataInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("external_category_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `external_category_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("external_category_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IntegrationMappingsListSalesCategoryMappingsResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IntegrationMappingsListSalesCategoryMappingsResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IntegrationMappingsListSalesCategoryMappingsResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IntegrationMappingsListSalesCategoryMappingsResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<IntegrationMappingsListSalesCategoryMappingsResponseDataInner>() {
           @Override
           public void write(JsonWriter out, IntegrationMappingsListSalesCategoryMappingsResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public IntegrationMappingsListSalesCategoryMappingsResponseDataInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             IntegrationMappingsListSalesCategoryMappingsResponseDataInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IntegrationMappingsListSalesCategoryMappingsResponseDataInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IntegrationMappingsListSalesCategoryMappingsResponseDataInner
  * @throws IOException if the JSON string is invalid with respect to IntegrationMappingsListSalesCategoryMappingsResponseDataInner
  */
  public static IntegrationMappingsListSalesCategoryMappingsResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IntegrationMappingsListSalesCategoryMappingsResponseDataInner.class);
  }

 /**
  * Convert an instance of IntegrationMappingsListSalesCategoryMappingsResponseDataInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

