/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private String date;

  public static final String SERIALIZED_NAME_VIOLATION_TYPE = "violation_type";
  @SerializedName(SERIALIZED_NAME_VIOLATION_TYPE)
  private String violationType;

  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  private Double cost;

  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner() {
  }

  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner date(String date) {
    
    
    
    
    this.date = date;
    return this;
  }

   /**
   * Exception date
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-01-30T00:00:00.000Z", value = "Exception date")

  public String getDate() {
    return date;
  }


  public void setDate(String date) {
    
    
    
    this.date = date;
  }


  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner violationType(String violationType) {
    
    
    
    
    this.violationType = violationType;
    return this;
  }

   /**
   * Violation type of this exception
   * @return violationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "spread_of_hours, split_shift", value = "Violation type of this exception")

  public String getViolationType() {
    return violationType;
  }


  public void setViolationType(String violationType) {
    
    
    
    this.violationType = violationType;
  }


  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner cost(Double cost) {
    
    
    
    
    this.cost = cost;
    return this;
  }

  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner cost(Integer cost) {
    
    
    
    
    this.cost = cost.doubleValue();
    return this;
  }

   /**
   * The cost of this exception (in dollars)
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "15.75", value = "The cost of this exception (in dollars)")

  public Double getCost() {
    return cost;
  }


  public void setCost(Double cost) {
    
    
    
    this.cost = cost;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner instance itself
   */
  public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner reportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner = (ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner) o;
    return Objects.equals(this.date, reportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.date) &&
        Objects.equals(this.violationType, reportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.violationType) &&
        Objects.equals(this.cost, reportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.cost)&&
        Objects.equals(this.additionalProperties, reportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, violationType, cost, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    violationType: ").append(toIndentedString(violationType)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("violation_type");
    openapiFields.add("cost");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner is not found in the empty JSON string", ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull()) && !jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
      if ((jsonObj.get("violation_type") != null && !jsonObj.get("violation_type").isJsonNull()) && !jsonObj.get("violation_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `violation_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("violation_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner>() {
           @Override
           public void write(JsonWriter out, ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner
  * @throws IOException if the JSON string is invalid with respect to ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner
  */
  public static ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner.class);
  }

 /**
  * Convert an instance of ReportsGetWorkedHoursWagesResponseUsersInnerWeeksInnerShiftsInnerComplianceExceptionsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

