/*
 * 7shifts API
 * 7shifts is a team management software designed for restaurants. We help managers and operators spend less time and effort scheduling their staff, reduce their monthly labor costs and improve team communication. The result is simplified team management, one shift at a time.  7shifts also offers free mobile apps (iOS and Android) allowing managers and employees to have everything at their fingertips.  Start your free trial or request a demo at www.7shifts.com.
 *
 * The version of the OpenAPI document: 2023-05-01
 * Contact: api-support@7shifts.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CompaniesGetByIdResponse;
import com.konfigthis.client.model.CompaniesGetLaborSettingsResponse;
import com.konfigthis.client.model.CompaniesListInactiveReasonsResponse;
import com.konfigthis.client.model.CompaniesListResponse;
import com.konfigthis.client.model.CompaniesUpdateCompanyByIdRequest;
import com.konfigthis.client.model.CompaniesUpdateCompanyByIdResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompaniesApi
 */
@Disabled
public class CompaniesApiTest {

    private static CompaniesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CompaniesApi(apiClient);
    }

    /**
     * Retrieve Company
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        Long id = null;
        String xApiVersion = null;
        UUID xCompanyGuid = null;
        CompaniesGetByIdResponse response = api.getById(id)
                .xApiVersion(xApiVersion)
                .xCompanyGuid(xCompanyGuid)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve Labor Settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLaborSettingsTest() throws ApiException {
        Long companyId = null;
        String xApiVersion = null;
        UUID xCompanyGuid = null;
        CompaniesGetLaborSettingsResponse response = api.getLaborSettings(companyId)
                .xApiVersion(xApiVersion)
                .xCompanyGuid(xCompanyGuid)
                .execute();
        // TODO: test validations
    }

    /**
     * List Companies
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String xApiVersion = null;
        UUID xCompanyGuid = null;
        String modifiedSince = null;
        CompaniesListResponse response = api.list()
                .xApiVersion(xApiVersion)
                .xCompanyGuid(xCompanyGuid)
                .modifiedSince(modifiedSince)
                .execute();
        // TODO: test validations
    }

    /**
     * List Inactive Reasons
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInactiveReasonsTest() throws ApiException {
        Long companyId = null;
        String xApiVersion = null;
        UUID xCompanyGuid = null;
        CompaniesListInactiveReasonsResponse response = api.listInactiveReasons(companyId)
                .xApiVersion(xApiVersion)
                .xCompanyGuid(xCompanyGuid)
                .execute();
        // TODO: test validations
    }

    /**
     * Update Company
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCompanyByIdTest() throws ApiException {
        Long id = null;
        String name = null;
        String country = null;
        String photo = null;
        String pos = null;
        String xApiVersion = null;
        UUID xCompanyGuid = null;
        CompaniesUpdateCompanyByIdResponse response = api.updateCompanyById(id)
                .name(name)
                .country(country)
                .photo(photo)
                .pos(pos)
                .xApiVersion(xApiVersion)
                .xCompanyGuid(xCompanyGuid)
                .execute();
        // TODO: test validations
    }

}
